services:
  - type: web
    name: veda-backend
    env: docker
    repo: https://github.com/purveshnileshbhadale/veda
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AI_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        value: veda-render-secret-2026
      - key: CORS_ORIGINS
        value: '["https://frontend-delta-weld-86.vercel.app"]'
