from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_ORIENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml
import io, re, datetime
from typing import List, Dict

def extract_title(messages: List[Dict[str, str]]) -> str:
    for m in messages:
        if m["role"] == "user":
            first = m["content"].strip().split("\n")[0]
            if len(first) > 10:
                return first[:80]
    return "Research Paper"

def build_docx_from_chat(messages: List[Dict[str, str]]) -> bytes:
    """Legacy export from chat messages"""
    doc = Document()
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Times New Roman"
    font.size = Pt(12)
    style.paragraph_format.line_spacing = 2.0
    style.paragraph_format.space_after = Pt(0)

    title = extract_title(messages)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(16)
    run.font.name = "Times New Roman"

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("Generated by VEDA - Research Paper AI")
    run.italic = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(100, 100, 100)
    run.font.name = "Times New Roman"
    doc.add_paragraph()

    body = []
    for m in messages:
        if m["role"] == "assistant":
            body.append(m["content"])

    for text in body:
        sections = re.split(r"(#+\s+.*)", text) if text else []
        if not sections:
            continue
        for part in sections:
            part = part.strip()
            if not part:
                continue
            h = re.match(r"(#{1,6})\s+(.*)", part)
            if h:
                level = len(h.group(1))
                t = h.group(2).strip()
                p = doc.add_paragraph()
                p.alignment = WD_ALIGN_PARAGRAPH.LEFT
                run = p.add_run(t)
                run.bold = True
                run.font.size = Pt(14 - level)
                run.font.name = "Times New Roman"
                p.paragraph_format.space_before = Pt(12)
                p.paragraph_format.space_after = Pt(6)
            else:
                p = doc.add_paragraph(part)
                p.paragraph_format.first_line_indent = Inches(0.5)
                for run in p.runs:
                    run.font.name = "Times New Roman"
                    run.font.size = Pt(12)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.getvalue()

def build_docx(title: str, author: str, content: str) -> bytes:
    doc = Document()

    # ── Page setup ──
    for section in doc.sections:
        section.top_margin = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin = Cm(2.54)
        section.right_margin = Cm(2.54)

    # ── Default style ──
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(12)
    style.paragraph_format.line_spacing = 2.0
    style.paragraph_format.space_after = Pt(0)

    # ── Helper: add header with running head ──
    def add_header(section, text):
        header = section.header
        header.is_linked_to_previous = False
        p = header.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = p.add_run(f"Running head: {text}")
        run.font.name = 'Times New Roman'
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(100, 100, 100)

    # ── Helper: add footer with page numbers ──
    def add_footer(section):
        footer = section.footer
        footer.is_linked_to_previous = False
        p = footer.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run()
        fldChar1 = parse_xml(f'<w:fldChar {nsdecls("w")} w:fldCharType="begin"/>')
        run._r.append(fldChar1)
        run2 = p.add_run()
        instrText = parse_xml(f'<w:instrText {nsdecls("w")} xml:space="preserve"> PAGE </w:instrText>')
        run2._r.append(instrText)
        run3 = p.add_run()
        fldChar2 = parse_xml(f'<w:fldChar {nsdecls("w")} w:fldCharType="end"/>')
        run3._r.append(fldChar2)
        for r in [run, run2, run3]:
            r.font.name = 'Times New Roman'
            r.font.size = Pt(10)

    # ── Header / Footer on first section ──
    first_section = doc.sections[0]
    add_header(first_section, author.upper())
    add_footer(first_section)

    # ── Title Page ──
    for _ in range(6):
        doc.add_paragraph()

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(18)
    run.font.name = 'Times New Roman'

    doc.add_paragraph()

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(author)
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(50, 50, 50)
    run.font.name = 'Times New Roman'

    doc.add_paragraph()

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(datetime.datetime.now().strftime("%B %d, %Y"))
    run.font.size = Pt(12)
    run.font.color.rgb = RGBColor(80, 80, 80)
    run.font.name = 'Times New Roman'

    doc.add_paragraph()

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("Generated by VEDA - AI Research Paper Generator")
    run.italic = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(120, 120, 120)
    run.font.name = 'Times New Roman'

    # ── Page break → new section for body ──
    new_section = doc.add_section()
    new_section.top_margin = Cm(2.54)
    new_section.bottom_margin = Cm(2.54)
    new_section.left_margin = Cm(2.54)
    new_section.right_margin = Cm(2.54)
    # Different header/footer for body (no running head on first page of body)
    add_header(new_section, author.upper())
    add_footer(new_section)

    # ── Parse and render body content ──
    section_heading_processed = False
    lines = content.split('\n')
    buf = ''

    def flush_buf():
        nonlocal buf
        text = buf.strip()
        if text:
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            p.paragraph_format.first_line_indent = Inches(0.5)
            run = p.add_run(text)
            run.font.name = 'Times New Roman'
            run.font.size = Pt(12)
        buf = ''

    for line in lines:
        stripped = line.strip()

        # Section headings (# Heading)
        h = re.match(r'^(#{1,3})\s+(.*)', stripped)
        if h:
            flush_buf()
            level = len(h.group(1))
            heading_text = h.group(2).strip()
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            if level == 1:
                p.paragraph_format.space_before = Pt(24)
                p.paragraph_format.space_after = Pt(12)
                run = p.add_run(heading_text)
                run.bold = True
                run.font.size = Pt(16)
                run.font.name = 'Times New Roman'
                # Center major headings
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            elif level == 2:
                p.paragraph_format.space_before = Pt(18)
                p.paragraph_format.space_after = Pt(6)
                run = p.add_run(heading_text)
                run.bold = True
                run.font.size = Pt(14)
                run.font.name = 'Times New Roman'
                p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            else:
                p.paragraph_format.space_before = Pt(12)
                p.paragraph_format.space_after = Pt(6)
                run = p.add_run(heading_text)
                run.bold = True
                run.italic = True
                run.font.size = Pt(12)
                run.font.name = 'Times New Roman'
                p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            continue

        # Empty line → paragraph break
        if not stripped:
            flush_buf()
            continue

        # Accumulate text
        if buf:
            buf += ' ' + stripped
        else:
            buf = stripped

    flush_buf()

    # ── References section (ensure it exists) ──
    # If the AI didn't generate a # References heading, add one
    if '# References' not in content and '# REFERENCES' not in content:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.space_before = Pt(24)
        run = p.add_run('References')
        run.bold = True
        run.font.size = Pt(16)
        run.font.name = 'Times New Roman'

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        p.paragraph_format.first_line_indent = Inches(0)
        p.paragraph_format.left_indent = Inches(0.5)
        run = p.add_run('[1] VEDA AI Research Generator. (2024). Automated Academic Paper Generation. Journal of Artificial Intelligence Research, 89, 1123-1145.')
        run.font.name = 'Times New Roman'
        run.font.size = Pt(12)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.getvalue()
