from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from typing import List, Dict
import io, re

def extract_title(messages: List[Dict[str, str]]) -> str:
    for m in messages:
        if m["role"] == "user":
            first = m["content"].strip().split("\n")[0]
            if len(first) > 10:
                return first[:80]
    return "Research Paper"

def build_docx(messages: List[Dict[str, str]]) -> bytes:
    doc = Document()

    style = doc.styles["Normal"]
    font = style.font
    font.name = "Times New Roman"
    font.size = Pt(12)
    style.paragraph_format.line_spacing = 2.0
    style.paragraph_format.space_after = Pt(0)

    title = extract_title(messages)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(16)
    run.font.name = "Times New Roman"

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("Generated by VEDA - Research Paper AI")
    run.italic = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(100, 100, 100)
    run.font.name = "Times New Roman"

    doc.add_paragraph()

    body = []
    for m in messages:
        if m["role"] == "assistant":
            body.append(m["content"])

    for text in body:
        sections = re.split(r"(#+\s+.*)", text) if text else []
        if not sections:
            continue
        for part in sections:
            part = part.strip()
            if not part:
                continue
            h = re.match(r"(#{1,6})\s+(.*)", part)
            if h:
                level = len(h.group(1))
                t = h.group(2).strip()
                p = doc.add_paragraph()
                p.alignment = WD_ALIGN_PARAGRAPH.LEFT
                run = p.add_run(t)
                run.bold = True
                run.font.size = Pt(14 - level)
                run.font.name = "Times New Roman"
                p.paragraph_format.space_before = Pt(12)
                p.paragraph_format.space_after = Pt(6)
            else:
                p = doc.add_paragraph(part)
                p.paragraph_format.first_line_indent = Inches(0.5)
                for run in p.runs:
                    run.font.name = "Times New Roman"
                    run.font.size = Pt(12)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.getvalue()
